### ISSUE TITLE
perbaikan dokumentasi 

### ISSUE THREAD

**Issue by pacenadhif777** [KeyouXZ/Skynomi#1]
apakah bisa kasih example cara pengisian item dan harga beli/jual dan contoh pemberian nama rank dan pengisian reward

**Comment by pacenadhif777** [comment]
prefix bawaan ilang pasa naikin rank

**Comment by KeyouXZ** [comment]
> prefix bawaan ilang pasa naikin rank

Iya karena di replace sama pluginnya di code ini

```csharp
        foreach (var key in rankConfig.Ranks)
            {
                string name = "rank_" + counter;
                string prefix = key.Value.Prefix ?? "";
                string suffix = key.Value.Suffix ?? "";
                string parent = (counter == 1) ? "default" : "rank_" + (counter-1).ToString();
                int[] color = key.Value.ChatColor;
                string chatColor = $"{color[0]},{color[1]},{color[2]}";
               

                counter++;

                if (!TShock.Groups.GroupExists(name))
                {
                    // Create the group
                    TShock.Groups.AddGroup(name, parent, TShock.Groups.GetGroupByName(parent).Permissions, "255,255,255");
                }
                
                // Assign prefix and suffix
                var group = TShock.Groups.GetGroupByName(name);
                if (group != null)
                {
                    group.Prefix = prefix;
                    group.Suffix = suffix;
                    group.ChatColor = chatColor;
                }
                else
                {
                    TShock.Log.ConsoleError("Failed to find group " + name + " after creation. Prefix and suffix were not applied.");
                }
            }
```

**Comment by KeyouXZ** [comment]
> apakah bisa kasih example cara pengisian item dan harga beli/jual dan contoh pemberian nama rank dan pengisian reward

bagian ini kah?

```json
{
  "Auto Broadcast Shop": false,
  "Broadcast Interval in Seconds": 60,
  "Shop Items": {
    "1": 100,
    "2": 200,
    "3": 300
  }
}
```

**Comment by pacenadhif777** [comment]
> > apakah bisa kasih example cara pengisian item dan harga beli/jual dan contoh pemberian nama rank dan pengisian reward
> 
> bagian ini kah?
> 
> ```json
> {
>   "Auto Broadcast Shop": false,
>   "Broadcast Interval in Seconds": 60,
>   "Shop Items": {
>     "1": 100,
>     "2": 200,
>     "3": 300
>   }
> }
> ```

iya itu gaada harga jual ya cuman beli?

**Comment by KeyouXZ** [comment]
> > > apakah bisa kasih example cara pengisian item dan harga beli/jual dan contoh pemberian nama rank dan pengisian reward
> > 
> > 
> > bagian ini kah?
> > ```json
> > {
> >   "Auto Broadcast Shop": false,
> >   "Broadcast Interval in Seconds": 60,
> >   "Shop Items": {
> >     "1": 100,
> >     "2": 200,
> >     "3": 300
> >   }
> > }
> > ```
> 
> iya itu gaada harga jual ya cuman beli?

iya, belum gua buat

**Comment by pacenadhif777** [comment]
atasi untuk pop up skyorb terkesan spam saat membunuh npc  yg jumlah banyak mungkin untuk transisinya diperlambat (anda bisa melihatnya ketika spawn king slime)  , untuk rank apakah bisa di custom formatnya example {1}{2}{3}:{4}, dan jgn replace yg sudah ada

**Comment by KeyouXZ** [comment]
> atasi untuk pop up skyorb terkesan spam saat membunuh npc yg jumlah banyak mungkin untuk transisinya diperlambat (anda bisa melihatnya ketika spawn king slime) , untuk rank apakah bisa di custom formatnya example {1}{2}{3}:{4}, dan jgn replace yg sudah ada

open new issue
